
server:
  port: 9090

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

spring:  application:    name: API-GATEWAY
  cloud:    gateway:      routes:      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:        - Path=/user/v1/**
        filters:        - name: CircuitBreaker
          args:            name: USER-SERVICE
            fallbackuri: forward:/userServiceFallBack      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/department/v1/** 
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBack

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream