server:
  port: 9293
  
spring:  application:    name: CONFIG-SERVER
  cloud:    config:      server:        git:          uri: https://github.com/gopi582/config-server
          clone-on-start: true
          force-pull: true